# Generated by Django 2.2.7 on 2019-11-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('january', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('february', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('march', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('april', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('may', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('june', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('july', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('august', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('september', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('october', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('november', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('december', models.CharField(choices=[('ยังไม่จ่าย', 'ยังไม่จ่าย'), ('จ่ายแล้ว', 'จ่ายแล้ว')], default='ยังไม่จ่าย', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=50)),
            ],
        ),
    ]
